title: Stay Hungry! Stay Foolish!
author: Sparky12x
email: sparky12x@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A fast-growing engineer.
  Have a fancy on Design.

# social links
twitter_username: your-twitter-handle
github_username:  sparky12x

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-slate
